;;;; Generated on 1/21/2026 at 11:17:43 (UTC+0).

(COMMON-LISP:DECLAIM
 (COMMON-LISP:OPTIMIZE (COMMON-LISP:SPEED 0) COMMON-LISP:SAFETY
  COMMON-LISP:DEBUG COMMON-LISP:COMPILATION-SPEED))

(COMMON-LISP:IN-PACKAGE #:MAGICL.BLAS-CFFI)

(COMMON-LISP:DECLAIM
 (COMMON-LISP:INLINE %%CAXPY %CAXPY %%CGEMM %CGEMM %%CGEMV %CGEMV %%CSCAL
  %CSCAL %%CSSCAL %CSSCAL %%DAXPY %DAXPY %%DGEMM %DGEMM %%DGEMV %DGEMV %%DSCAL
  %DSCAL %%SAXPY %SAXPY %%SGEMM %SGEMM %%SGEMV %SGEMV %%SSCAL %SSCAL %%ZAXPY
  %ZAXPY %%ZDSCAL %ZDSCAL %%ZGEMM %ZGEMM %%ZGEMV %ZGEMV %%ZSCAL %ZSCAL))

(CFFI:DEFCFUN ("caxpy_" %%CAXPY :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (CA :POINTER)
  (CX :POINTER)
  (INCX :POINTER)
  (CY :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %CAXPY (N CA CX INCX CY INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CAXPY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) CA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        CX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        CY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF1 ':INT32)
                              (CA-REF2 'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (INCX-REF4 ':INT32) (INCY-REF6 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF1 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              CA-REF2 MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART CA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART CA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF4 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF6 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((CX-REF3 CX) (CY-REF5 CY))
      (%%CAXPY N-REF1 CA-REF2 CX-REF3 INCX-REF4 CY-REF5 INCY-REF6))))

(CFFI:DEFCFUN ("cgemm_" %%CGEMM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (TRANSA :STRING)
  (TRANSB :STRING)
  (M :POINTER)
  (N :POINTER)
  (K :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (B :POINTER)
  (LDB :POINTER)
  (BETA :POINTER)
  (C :POINTER)
  (LDC :POINTER))

(COMMON-LISP:DEFUN %CGEMM (TRANSA TRANSB M N K ALPHA A LDA B LDB BETA C LDC)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CGEMM)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSA)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSB)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) K)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        B)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDB)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        C)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDC))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF9 ':INT32) (N-REF10 ':INT32)
                              (K-REF11 ':INT32)
                              (ALPHA-REF12
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (LDA-REF14 ':INT32) (LDB-REF16 ':INT32)
                              (BETA-REF17
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (LDC-REF19 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF9 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF10 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF K-REF11 :INT32) K)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ALPHA-REF12
                              MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ALPHA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ALPHA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF14 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDB-REF16 :INT32) LDB)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              BETA-REF17 MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART BETA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART BETA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDC-REF19 :INT32) LDC)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF13 A) (B-REF15 B) (C-REF18 C))
      (%%CGEMM TRANSA TRANSB M-REF9 N-REF10 K-REF11 ALPHA-REF12 A-REF13
       LDA-REF14 B-REF15 LDB-REF16 BETA-REF17 C-REF18 LDC-REF19))))

(CFFI:DEFCFUN ("cgemv_" %%CGEMV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (TRANS :STRING)
  (M :POINTER)
  (N :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (X :POINTER)
  (INCX :POINTER)
  (BETA :POINTER)
  (Y :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %CGEMV (TRANS M N ALPHA A LDA X INCX BETA Y INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CGEMV)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        X)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        Y)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF21 ':INT32) (N-REF22 ':INT32)
                              (ALPHA-REF23
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (LDA-REF25 ':INT32) (INCX-REF27 ':INT32)
                              (BETA-REF28
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (INCY-REF30 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF21 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF22 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ALPHA-REF23
                              MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ALPHA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ALPHA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF25 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF27 :INT32) INCX)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              BETA-REF28 MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART BETA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART BETA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF30 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF24 A) (X-REF26 X) (Y-REF29 Y))
      (%%CGEMV TRANS M-REF21 N-REF22 ALPHA-REF23 A-REF24 LDA-REF25 X-REF26
       INCX-REF27 BETA-REF28 Y-REF29 INCY-REF30))))

(CFFI:DEFCFUN ("cscal_" %%CSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (CA :POINTER)
  (CX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %CSCAL (N CA CX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT) CA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        CX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF31 ':INT32)
                              (CA-REF32
                               'MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
                              (INCX-REF34 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF31 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              CA-REF32 MAGICL.CFFI-TYPES:COMPLEX-SINGLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART CA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART CA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF34 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((CX-REF33 CX))
      (%%CSCAL N-REF31 CA-REF32 CX-REF33 INCX-REF34))))

(CFFI:DEFCFUN ("csscal_" %%CSSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (SA :POINTER)
  (CX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %CSSCAL (N SA CX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%CSSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT SA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:SINGLE-FLOAT)
                         (COMMON-LISP:*))
                        CX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF35 ':INT32) (SA-REF36 ':FLOAT)
                              (INCX-REF38 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF35 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF SA-REF36 :FLOAT) SA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF38 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((CX-REF37 CX))
      (%%CSSCAL N-REF35 SA-REF36 CX-REF37 INCX-REF38))))

(CFFI:DEFCFUN ("daxpy_" %%DAXPY :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (DA :POINTER)
  (DX :POINTER)
  (INCX :POINTER)
  (DY :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %DAXPY (N DA DX INCX DY INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DAXPY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT DA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) DX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) DY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF39 ':INT32) (DA-REF40 ':DOUBLE)
                              (INCX-REF42 ':INT32) (INCY-REF44 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF39 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF DA-REF40 :DOUBLE) DA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF42 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF44 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((DX-REF41 DX) (DY-REF43 DY))
      (%%DAXPY N-REF39 DA-REF40 DX-REF41 INCX-REF42 DY-REF43 INCY-REF44))))

(CFFI:DEFCFUN ("dgemm_" %%DGEMM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (TRANSA :STRING)
  (TRANSB :STRING)
  (M :POINTER)
  (N :POINTER)
  (K :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (B :POINTER)
  (LDB :POINTER)
  (BETA :POINTER)
  (C :POINTER)
  (LDC :POINTER))

(COMMON-LISP:DEFUN %DGEMM (TRANSA TRANSB M N K ALPHA A LDA B LDB BETA C LDC)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGEMM)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSA)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSB)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) K)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) B)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDB)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) C)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDC))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF47 ':INT32) (N-REF48 ':INT32)
                              (K-REF49 ':INT32) (ALPHA-REF50 ':DOUBLE)
                              (LDA-REF52 ':INT32) (LDB-REF54 ':INT32)
                              (BETA-REF55 ':DOUBLE) (LDC-REF57 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF47 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF48 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF K-REF49 :INT32) K)
    (COMMON-LISP:SETF (CFFI:MEM-REF ALPHA-REF50 :DOUBLE) ALPHA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF52 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDB-REF54 :INT32) LDB)
    (COMMON-LISP:SETF (CFFI:MEM-REF BETA-REF55 :DOUBLE) BETA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDC-REF57 :INT32) LDC)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF51 A) (B-REF53 B) (C-REF56 C))
      (%%DGEMM TRANSA TRANSB M-REF47 N-REF48 K-REF49 ALPHA-REF50 A-REF51
       LDA-REF52 B-REF53 LDB-REF54 BETA-REF55 C-REF56 LDC-REF57))))

(CFFI:DEFCFUN ("dgemv_" %%DGEMV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (TRANS :STRING)
  (M :POINTER)
  (N :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (X :POINTER)
  (INCX :POINTER)
  (BETA :POINTER)
  (Y :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %DGEMV (TRANS M N ALPHA A LDA X INCX BETA Y INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGEMV)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) X)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF59 ':INT32) (N-REF60 ':INT32)
                              (ALPHA-REF61 ':DOUBLE) (LDA-REF63 ':INT32)
                              (INCX-REF65 ':INT32) (BETA-REF66 ':DOUBLE)
                              (INCY-REF68 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF59 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF60 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF ALPHA-REF61 :DOUBLE) ALPHA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF63 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF65 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF BETA-REF66 :DOUBLE) BETA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF68 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF62 A) (X-REF64 X) (Y-REF67 Y))
      (%%DGEMV TRANS M-REF59 N-REF60 ALPHA-REF61 A-REF62 LDA-REF63 X-REF64
       INCX-REF65 BETA-REF66 Y-REF67 INCY-REF68))))

(CFFI:DEFCFUN ("dscal_" %%DSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (DA :POINTER)
  (DX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %DSCAL (N DA DX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT DA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) DX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF69 ':INT32) (DA-REF70 ':DOUBLE)
                              (INCX-REF72 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF69 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF DA-REF70 :DOUBLE) DA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF72 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((DX-REF71 DX))
      (%%DSCAL N-REF69 DA-REF70 DX-REF71 INCX-REF72))))

(CFFI:DEFCFUN ("saxpy_" %%SAXPY :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (SA :POINTER)
  (SX :POINTER)
  (INCX :POINTER)
  (SY :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %SAXPY (N SA SX INCX SY INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%SAXPY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT SA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) SX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) SY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF73 ':INT32) (SA-REF74 ':FLOAT)
                              (INCX-REF76 ':INT32) (INCY-REF78 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF73 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF SA-REF74 :FLOAT) SA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF76 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF78 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((SX-REF75 SX) (SY-REF77 SY))
      (%%SAXPY N-REF73 SA-REF74 SX-REF75 INCX-REF76 SY-REF77 INCY-REF78))))

(CFFI:DEFCFUN ("sgemm_" %%SGEMM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (TRANSA :STRING)
  (TRANSB :STRING)
  (M :POINTER)
  (N :POINTER)
  (K :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (B :POINTER)
  (LDB :POINTER)
  (BETA :POINTER)
  (C :POINTER)
  (LDC :POINTER))

(COMMON-LISP:DEFUN %SGEMM (TRANSA TRANSB M N K ALPHA A LDA B LDB BETA C LDC)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%SGEMM)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSA)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSB)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) K)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) B)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDB)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) C)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDC))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF81 ':INT32) (N-REF82 ':INT32)
                              (K-REF83 ':INT32) (ALPHA-REF84 ':FLOAT)
                              (LDA-REF86 ':INT32) (LDB-REF88 ':INT32)
                              (BETA-REF89 ':FLOAT) (LDC-REF91 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF81 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF82 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF K-REF83 :INT32) K)
    (COMMON-LISP:SETF (CFFI:MEM-REF ALPHA-REF84 :FLOAT) ALPHA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF86 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDB-REF88 :INT32) LDB)
    (COMMON-LISP:SETF (CFFI:MEM-REF BETA-REF89 :FLOAT) BETA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDC-REF91 :INT32) LDC)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF85 A) (B-REF87 B) (C-REF90 C))
      (%%SGEMM TRANSA TRANSB M-REF81 N-REF82 K-REF83 ALPHA-REF84 A-REF85
       LDA-REF86 B-REF87 LDB-REF88 BETA-REF89 C-REF90 LDC-REF91))))

(CFFI:DEFCFUN ("sgemv_" %%SGEMV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (TRANS :STRING)
  (M :POINTER)
  (N :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (X :POINTER)
  (INCX :POINTER)
  (BETA :POINTER)
  (Y :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %SGEMV (TRANS M N ALPHA A LDA X INCX BETA Y INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%SGEMV)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) X)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) Y)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF93 ':INT32) (N-REF94 ':INT32)
                              (ALPHA-REF95 ':FLOAT) (LDA-REF97 ':INT32)
                              (INCX-REF99 ':INT32) (BETA-REF100 ':FLOAT)
                              (INCY-REF102 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF93 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF94 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF ALPHA-REF95 :FLOAT) ALPHA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF97 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF99 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF BETA-REF100 :FLOAT) BETA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF102 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF96 A) (X-REF98 X)
                                            (Y-REF101 Y))
      (%%SGEMV TRANS M-REF93 N-REF94 ALPHA-REF95 A-REF96 LDA-REF97 X-REF98
       INCX-REF99 BETA-REF100 Y-REF101 INCY-REF102))))

(CFFI:DEFCFUN ("sscal_" %%SSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (SA :POINTER)
  (SX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %SSCAL (N SA SX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%SSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:SINGLE-FLOAT SA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:SINGLE-FLOAT) SX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF103 ':INT32) (SA-REF104 ':FLOAT)
                              (INCX-REF106 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF103 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF SA-REF104 :FLOAT) SA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF106 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((SX-REF105 SX))
      (%%SSCAL N-REF103 SA-REF104 SX-REF105 INCX-REF106))))

(CFFI:DEFCFUN ("zaxpy_" %%ZAXPY :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (ZA :POINTER)
  (ZX :POINTER)
  (INCX :POINTER)
  (ZY :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %ZAXPY (N ZA ZX INCX ZY INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZAXPY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) ZA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        ZX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        ZY)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF107 ':INT32)
                              (ZA-REF108
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (INCX-REF110 ':INT32) (INCY-REF112 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF107 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ZA-REF108 MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ZA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ZA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF110 :INT32) INCX)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF112 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((ZX-REF109 ZX) (ZY-REF111 ZY))
      (%%ZAXPY N-REF107 ZA-REF108 ZX-REF109 INCX-REF110 ZY-REF111
       INCY-REF112))))

(CFFI:DEFCFUN ("zdscal_" %%ZDSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (DA :POINTER)
  (ZX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %ZDSCAL (N DA ZX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZDSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT DA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        ZX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF113 ':INT32) (DA-REF114 ':DOUBLE)
                              (INCX-REF116 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF113 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF DA-REF114 :DOUBLE) DA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF116 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((ZX-REF115 ZX))
      (%%ZDSCAL N-REF113 DA-REF114 ZX-REF115 INCX-REF116))))

(CFFI:DEFCFUN ("zgemm_" %%ZGEMM :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (TRANSA :STRING)
  (TRANSB :STRING)
  (M :POINTER)
  (N :POINTER)
  (K :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (B :POINTER)
  (LDB :POINTER)
  (BETA :POINTER)
  (C :POINTER)
  (LDC :POINTER))

(COMMON-LISP:DEFUN %ZGEMM (TRANSA TRANSB M N K ALPHA A LDA B LDB BETA C LDC)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGEMM)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSA)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANSB)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) K)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        B)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDB)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        C)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDC))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF119 ':INT32) (N-REF120 ':INT32)
                              (K-REF121 ':INT32)
                              (ALPHA-REF122
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (LDA-REF124 ':INT32) (LDB-REF126 ':INT32)
                              (BETA-REF127
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (LDC-REF129 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF119 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF120 :INT32) N)
    (COMMON-LISP:SETF (CFFI:MEM-REF K-REF121 :INT32) K)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ALPHA-REF122
                              MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ALPHA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ALPHA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF124 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDB-REF126 :INT32) LDB)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              BETA-REF127
                              MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART BETA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART BETA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDC-REF129 :INT32) LDC)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF123 A) (B-REF125 B)
                                            (C-REF128 C))
      (%%ZGEMM TRANSA TRANSB M-REF119 N-REF120 K-REF121 ALPHA-REF122 A-REF123
       LDA-REF124 B-REF125 LDB-REF126 BETA-REF127 C-REF128 LDC-REF129))))

(CFFI:DEFCFUN ("zgemv_" %%ZGEMV :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (TRANS :STRING)
  (M :POINTER)
  (N :POINTER)
  (ALPHA :POINTER)
  (A :POINTER)
  (LDA :POINTER)
  (X :POINTER)
  (INCX :POINTER)
  (BETA :POINTER)
  (Y :POINTER)
  (INCY :POINTER))

(COMMON-LISP:DEFUN %ZGEMV (TRANS M N ALPHA A LDA X INCX BETA Y INCY)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGEMV)
                       (COMMON-LISP:TYPE COMMON-LISP:STRING TRANS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) ALPHA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        A)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        X)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) BETA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        Y)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCY))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF131 ':INT32) (N-REF132 ':INT32)
                              (ALPHA-REF133
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (LDA-REF135 ':INT32) (INCX-REF137 ':INT32)
                              (BETA-REF138
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (INCY-REF140 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF131 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF132 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ALPHA-REF133
                              MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ALPHA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ALPHA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF LDA-REF135 :INT32) LDA)
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF137 :INT32) INCX)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              BETA-REF138
                              MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART BETA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART BETA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCY-REF140 :INT32) INCY)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((A-REF134 A) (X-REF136 X)
                                            (Y-REF139 Y))
      (%%ZGEMV TRANS M-REF131 N-REF132 ALPHA-REF133 A-REF134 LDA-REF135
       X-REF136 INCX-REF137 BETA-REF138 Y-REF139 INCY-REF140))))

(CFFI:DEFCFUN ("zscal_" %%ZSCAL :LIBRARY MAGICL.FOREIGN-LIBRARIES:LIBBLAS)
    :VOID
  (N :POINTER)
  (ZA :POINTER)
  (ZX :POINTER)
  (INCX :POINTER))

(COMMON-LISP:DEFUN %ZSCAL (N ZA ZX INCX)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZSCAL)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) N)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT) ZA)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        ZX)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) INCX))
  (CFFI:WITH-FOREIGN-OBJECTS ((N-REF141 ':INT32)
                              (ZA-REF142
                               'MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
                              (INCX-REF144 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF N-REF141 :INT32) N)
    (CFFI:WITH-FOREIGN-SLOTS ((COMMON-LISP:REAL MAGICL.CFFI-TYPES::IMAG)
                              ZA-REF142 MAGICL.CFFI-TYPES:COMPLEX-DOUBLE-FLOAT)
      (COMMON-LISP:SETF COMMON-LISP:REAL (COMMON-LISP:REALPART ZA)
                        MAGICL.CFFI-TYPES::IMAG (COMMON-LISP:IMAGPART ZA)))
    (COMMON-LISP:SETF (CFFI:MEM-REF INCX-REF144 :INT32) INCX)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((ZX-REF143 ZX))
      (%%ZSCAL N-REF141 ZA-REF142 ZX-REF143 INCX-REF144))))

(COMMON-LISP:DECLAIM
 (COMMON-LISP:NOTINLINE %%CAXPY %CAXPY %%CGEMM %CGEMM %%CGEMV %CGEMV %%CSCAL
  %CSCAL %%CSSCAL %CSSCAL %%DAXPY %DAXPY %%DGEMM %DGEMM %%DGEMV %DGEMV %%DSCAL
  %DSCAL %%SAXPY %SAXPY %%SGEMM %SGEMM %%SGEMV %SGEMV %%SSCAL %SSCAL %%ZAXPY
  %ZAXPY %%ZDSCAL %ZDSCAL %%ZGEMM %ZGEMM %%ZGEMV %ZGEMV %%ZSCAL %ZSCAL))

(MAGICL.FOREIGN-LIBRARIES:TRACK-SYMBOLS 'MAGICL.FOREIGN-LIBRARIES:LIBBLAS
                                        '(("CAXPY" "caxpy_" %%CAXPY %CAXPY)
                                          ("CGEMM" "cgemm_" %%CGEMM %CGEMM)
                                          ("CGEMV" "cgemv_" %%CGEMV %CGEMV)
                                          ("CSCAL" "cscal_" %%CSCAL %CSCAL)
                                          ("CSSCAL" "csscal_" %%CSSCAL %CSSCAL)
                                          ("DAXPY" "daxpy_" %%DAXPY %DAXPY)
                                          ("DGEMM" "dgemm_" %%DGEMM %DGEMM)
                                          ("DGEMV" "dgemv_" %%DGEMV %DGEMV)
                                          ("DSCAL" "dscal_" %%DSCAL %DSCAL)
                                          ("SAXPY" "saxpy_" %%SAXPY %SAXPY)
                                          ("SGEMM" "sgemm_" %%SGEMM %SGEMM)
                                          ("SGEMV" "sgemv_" %%SGEMV %SGEMV)
                                          ("SSCAL" "sscal_" %%SSCAL %SSCAL)
                                          ("ZAXPY" "zaxpy_" %%ZAXPY %ZAXPY)
                                          ("ZDSCAL" "zdscal_" %%ZDSCAL %ZDSCAL)
                                          ("ZGEMM" "zgemm_" %%ZGEMM %ZGEMM)
                                          ("ZGEMV" "zgemv_" %%ZGEMV %ZGEMV)
                                          ("ZSCAL" "zscal_" %%ZSCAL %ZSCAL)))

(COMMON-LISP:EXPORT
 '(%CAXPY %CGEMM %CGEMV %CSCAL %CSSCAL %DAXPY %DGEMM %DGEMV %DSCAL %SAXPY
   %SGEMM %SGEMV %SSCAL %ZAXPY %ZDSCAL %ZGEMM %ZGEMV %ZSCAL)
 '#:MAGICL.BLAS-CFFI)

;;; End of file.
