;;;; Generated on 1/21/2026 at 11:17:43 (UTC+0).

(COMMON-LISP:DECLAIM
 (COMMON-LISP:OPTIMIZE (COMMON-LISP:SPEED 0) COMMON-LISP:SAFETY
  COMMON-LISP:DEBUG COMMON-LISP:COMPILATION-SPEED))

(COMMON-LISP:IN-PACKAGE #:MAGICL.EXPOKIT-CFFI)

(COMMON-LISP:DECLAIM
 (COMMON-LISP:INLINE %%DGPADM %DGPADM %%DSPADM %DSPADM %%ZGPADM %ZGPADM
  %%ZHPADM %ZHPADM %%DGCHBV %DGCHBV %%DNCHBV %DNCHBV %%DSCHBV %DSCHBV %%ZGCHBV
  %ZGCHBV %%ZNCHBV %ZNCHBV))

(CFFI:DEFCFUN ("dgpadm_" %%DGPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DEFUN %DGPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT)
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF2075 ':INT32) (M-REF2076 ':INT32)
                              (T-REF2077 ':DOUBLE) (LDH-REF2079 ':INT32)
                              (LWSP-REF2081 ':INT32) (IEXPH-REF2083 ':INT32)
                              (NS-REF2084 ':INT32) (IFLAG-REF2085 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF2075 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2076 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2077 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2079 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF2081 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF2083 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF2084 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF2085 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2078 H) (WSP-REF2080 WSP)
                                            (IPIV-REF2082 IPIV))
      (%%DGPADM IDEG-REF2075 M-REF2076 T-REF2077 H-REF2078 LDH-REF2079
       WSP-REF2080 LWSP-REF2081 IPIV-REF2082 IEXPH-REF2083 NS-REF2084
       IFLAG-REF2085))))

(CFFI:DEFCFUN ("dspadm_" %%DSPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DEFUN %DSPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DSPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT)
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF2086 ':INT32) (M-REF2087 ':INT32)
                              (T-REF2088 ':DOUBLE) (LDH-REF2090 ':INT32)
                              (LWSP-REF2092 ':INT32) (IEXPH-REF2094 ':INT32)
                              (NS-REF2095 ':INT32) (IFLAG-REF2096 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF2086 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2087 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2088 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2090 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF2092 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF2094 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF2095 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF2096 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2089 H) (WSP-REF2091 WSP)
                                            (IPIV-REF2093 IPIV))
      (%%DSPADM IDEG-REF2086 M-REF2087 T-REF2088 H-REF2089 LDH-REF2090
       WSP-REF2091 LWSP-REF2092 IPIV-REF2093 IEXPH-REF2094 NS-REF2095
       IFLAG-REF2096))))

(CFFI:DEFCFUN ("zgpadm_" %%ZGPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DEFUN %ZGPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF2097 ':INT32) (M-REF2098 ':INT32)
                              (T-REF2099 ':DOUBLE) (LDH-REF2101 ':INT32)
                              (LWSP-REF2103 ':INT32) (IEXPH-REF2105 ':INT32)
                              (NS-REF2106 ':INT32) (IFLAG-REF2107 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF2097 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2098 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2099 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2101 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF2103 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF2105 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF2106 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF2107 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2100 H) (WSP-REF2102 WSP)
                                            (IPIV-REF2104 IPIV))
      (%%ZGPADM IDEG-REF2097 M-REF2098 T-REF2099 H-REF2100 LDH-REF2101
       WSP-REF2102 LWSP-REF2103 IPIV-REF2104 IEXPH-REF2105 NS-REF2106
       IFLAG-REF2107))))

(CFFI:DEFCFUN ("zhpadm_" %%ZHPADM :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (IDEG :POINTER)
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (WSP :POINTER)
  (LWSP :POINTER)
  (IPIV :POINTER)
  (IEXPH :POINTER)
  (NS :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DEFUN %ZHPADM (IDEG M T H LDH WSP LWSP IPIV IEXPH NS IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZHPADM)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IDEG)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LWSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IPIV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IEXPH)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) NS)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((IDEG-REF2108 ':INT32) (M-REF2109 ':INT32)
                              (T-REF2110 ':DOUBLE) (LDH-REF2112 ':INT32)
                              (LWSP-REF2114 ':INT32) (IEXPH-REF2116 ':INT32)
                              (NS-REF2117 ':INT32) (IFLAG-REF2118 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF IDEG-REF2108 :INT32) IDEG)
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2109 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2110 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2112 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF LWSP-REF2114 :INT32) LWSP)
    (COMMON-LISP:SETF (CFFI:MEM-REF IEXPH-REF2116 :INT32) IEXPH)
    (COMMON-LISP:SETF (CFFI:MEM-REF NS-REF2117 :INT32) NS)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF2118 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2111 H) (WSP-REF2113 WSP)
                                            (IPIV-REF2115 IPIV))
      (%%ZHPADM IDEG-REF2108 M-REF2109 T-REF2110 H-REF2111 LDH-REF2112
       WSP-REF2113 LWSP-REF2114 IPIV-REF2115 IEXPH-REF2116 NS-REF2117
       IFLAG-REF2118))))

(CFFI:DEFCFUN ("dgchbv_" %%DGCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DEFUN %DGCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DGCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF2119 ':INT32) (T-REF2120 ':DOUBLE)
                              (LDH-REF2122 ':INT32) (IFLAG-REF2126 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2119 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2120 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2122 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF2126 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2121 H) (Y-REF2123 Y)
                                            (WSP-REF2124 WSP)
                                            (IWSP-REF2125 IWSP))
      (%%DGCHBV M-REF2119 T-REF2120 H-REF2121 LDH-REF2122 Y-REF2123 WSP-REF2124
       IWSP-REF2125 IFLAG-REF2126))))

(CFFI:DEFCFUN ("dnchbv_" %%DNCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER))

(COMMON-LISP:DEFUN %DNCHBV (M T H LDH Y WSP)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DNCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF2127 ':INT32) (T-REF2128 ':DOUBLE)
                              (LDH-REF2130 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2127 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2128 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2130 :INT32) LDH)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2129 H) (Y-REF2131 Y)
                                            (WSP-REF2132 WSP))
      (%%DNCHBV M-REF2127 T-REF2128 H-REF2129 LDH-REF2130 Y-REF2131
       WSP-REF2132))))

(CFFI:DEFCFUN ("dschbv_" %%DSCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DEFUN %DSCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%DSCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY COMMON-LISP:DOUBLE-FLOAT) Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF2133 ':INT32) (T-REF2134 ':DOUBLE)
                              (LDH-REF2136 ':INT32) (IFLAG-REF2140 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2133 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2134 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2136 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF2140 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2135 H) (Y-REF2137 Y)
                                            (WSP-REF2138 WSP)
                                            (IWSP-REF2139 IWSP))
      (%%DSCHBV M-REF2133 T-REF2134 H-REF2135 LDH-REF2136 Y-REF2137 WSP-REF2138
       IWSP-REF2139 IFLAG-REF2140))))

(CFFI:DEFCFUN ("zgchbv_" %%ZGCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER)
  (IWSP :POINTER)
  (IFLAG :POINTER))

(COMMON-LISP:DEFUN %ZGCHBV (M T H LDH Y WSP IWSP IFLAG)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZGCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY (COMMON-LISP:SIGNED-BYTE 32)
                         (COMMON-LISP:*))
                        IWSP)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) IFLAG))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF2141 ':INT32) (T-REF2142 ':DOUBLE)
                              (LDH-REF2144 ':INT32) (IFLAG-REF2148 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2141 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2142 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2144 :INT32) LDH)
    (COMMON-LISP:SETF (CFFI:MEM-REF IFLAG-REF2148 :INT32) IFLAG)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2143 H) (Y-REF2145 Y)
                                            (WSP-REF2146 WSP)
                                            (IWSP-REF2147 IWSP))
      (%%ZGCHBV M-REF2141 T-REF2142 H-REF2143 LDH-REF2144 Y-REF2145 WSP-REF2146
       IWSP-REF2147 IFLAG-REF2148))))

(CFFI:DEFCFUN ("znchbv_" %%ZNCHBV :LIBRARY MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT)
    :VOID
  (M :POINTER)
  (T :POINTER)
  (H :POINTER)
  (LDH :POINTER)
  (Y :POINTER)
  (WSP :POINTER))

(COMMON-LISP:DEFUN %ZNCHBV (M T H LDH Y WSP)
  (COMMON-LISP:DECLARE (COMMON-LISP:INLINE %%ZNCHBV)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) M)
                       (COMMON-LISP:TYPE COMMON-LISP:DOUBLE-FLOAT T)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        H)
                       (COMMON-LISP:TYPE (COMMON-LISP:SIGNED-BYTE 32) LDH)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        Y)
                       (COMMON-LISP:TYPE
                        (COMMON-LISP:SIMPLE-ARRAY
                         (COMMON-LISP:COMPLEX COMMON-LISP:DOUBLE-FLOAT)
                         (COMMON-LISP:*))
                        WSP))
  (CFFI:WITH-FOREIGN-OBJECTS ((M-REF2149 ':INT32) (T-REF2150 ':DOUBLE)
                              (LDH-REF2152 ':INT32))
    (COMMON-LISP:SETF (CFFI:MEM-REF M-REF2149 :INT32) M)
    (COMMON-LISP:SETF (CFFI:MEM-REF T-REF2150 :DOUBLE) T)
    (COMMON-LISP:SETF (CFFI:MEM-REF LDH-REF2152 :INT32) LDH)
    (MAGICL.CFFI-TYPES:WITH-ARRAY-POINTERS ((H-REF2151 H) (Y-REF2153 Y)
                                            (WSP-REF2154 WSP))
      (%%ZNCHBV M-REF2149 T-REF2150 H-REF2151 LDH-REF2152 Y-REF2153
       WSP-REF2154))))

(COMMON-LISP:DECLAIM
 (COMMON-LISP:NOTINLINE %%DGPADM %DGPADM %%DSPADM %DSPADM %%ZGPADM %ZGPADM
  %%ZHPADM %ZHPADM %%DGCHBV %DGCHBV %%DNCHBV %DNCHBV %%DSCHBV %DSCHBV %%ZGCHBV
  %ZGCHBV %%ZNCHBV %ZNCHBV))

(MAGICL.FOREIGN-LIBRARIES:TRACK-SYMBOLS 'MAGICL.FOREIGN-LIBRARIES::LIBEXPOKIT
                                        '(("DGPADM" "dgpadm_" %%DGPADM %DGPADM)
                                          ("DSPADM" "dspadm_" %%DSPADM %DSPADM)
                                          ("ZGPADM" "zgpadm_" %%ZGPADM %ZGPADM)
                                          ("ZHPADM" "zhpadm_" %%ZHPADM %ZHPADM)
                                          ("DGCHBV" "dgchbv_" %%DGCHBV %DGCHBV)
                                          ("DNCHBV" "dnchbv_" %%DNCHBV %DNCHBV)
                                          ("DSCHBV" "dschbv_" %%DSCHBV %DSCHBV)
                                          ("ZGCHBV" "zgchbv_" %%ZGCHBV %ZGCHBV)
                                          ("ZNCHBV" "znchbv_" %%ZNCHBV
                                           %ZNCHBV)))

(COMMON-LISP:EXPORT
 '(%DGPADM %DSPADM %ZGPADM %ZHPADM %DGCHBV %DNCHBV %DSCHBV %ZGCHBV %ZNCHBV)
 '#:MAGICL.EXPOKIT-CFFI)

;;; End of file.
